---
title: "APA & Co project | SM3. Data relating to all the 6MWT, IPAQ-SF, and EMAPS measurements during the study"
output: 
  html_document:
    theme: cosmo
    toc: yes
    toc_depth: 2
    toc_float: yes
    number_sections: yes
    df_print: paged
toc-title: "Table of content"

---
```{css, echo=FALSE}
.title {
  font-weight: bold;
}


h1 {
  font-size: 25px;
  font-weight: bold;
}
h2 {
  font-size: 23px;
  font-weight: bold;
}
h3 {
  font-size: 21px;
}
p.caption {
  color: #777;
  margin-top: 10px;
}
p code {
  white-space: inherit;
}
pre {
  word-break: normal;
  word-wrap: normal;
}
pre code {
  white-space: inherit;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
ggplot2::theme_set(ggplot2::theme_bw())
```

# Figures
## 6MWT
```{r}
targets::tar_read(p_6MWT_all)
```

\newpage

## IPAQ-SF
```{r}
targets::tar_read(p_IPAQ_all)
```

\newpage

## EMAPS
```{r}
targets::tar_read(p_EMAPS_all)
```

\newpage

# Descriptive statistics
```{r}
targets::tar_read(table_all_desc_stat)
```


