---
title: "APA&Co project | SM5. Data relating to the shift and difference asymmetry functions to describe the change in 6MWT distance, IPAQ-SF MET-min/week, and EMAPS scores"
output: 
  html_document:
    theme: cosmo
    toc: yes
    toc_depth: 2
    toc_float: yes
    number_sections: yes
    df_print: paged
    code_folding: hide
toc-title: "Table of content"
---
```{css, echo=FALSE}
.title {
  font-weight: bold;
}


h1 {
  font-size: 25px;
  font-weight: bold;
}
h2 {
  font-size: 23px;
  font-weight: bold;
}
h3 {
  font-size: 21px;
}
p.caption {
  color: #777;
  margin-top: 10px;
}
p code {
  white-space: inherit;
}
pre {
  word-break: normal;
  word-wrap: normal;
}
pre code {
  white-space: inherit;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r, include=FALSE}
targets::tar_load(change_6MWT)
targets::tar_load(change_IPAQ)
targets::tar_load(change_EMAPS)

list_titles <- list(
  "6MWT distance",
  "IPAQ-SF MET-min / week",
  "EMAPS | Intrinsic motivation",
  "EMAPS | Integrated regulation",
  "EMAPS | Identified regulation",
  "EMAPS | Introjected regulation",
  "EMAPS | External regulation",
  "EMAPS | Amotivation"
)
  
list_tables <- list(
  change_6MWT,
  change_IPAQ,
  change_EMAPS[[1]],
  change_EMAPS[[2]],
  change_EMAPS[[3]],
  change_EMAPS[[4]],
  change_EMAPS[[5]],
  change_EMAPS[[6]]
)

legend_sf <- "q = quantile; ci.low = lower bounds of the confidence intervals; ci.up = upper bounds of the confidence intervals; adj_p_value_bh = p value adjusted for multiple comparisons using the Benjamini-Hochberg False Discovery Rate method."

legend_asym <- "Est_q = quantiles of differences; Est_1.minus.q = 1 - quantiles of differences; SUM = sum of quantiles; ci.low = lower bounds of the confidence intervals; ci.up = upper bounds of the confidence intervals; adj_p_value_bh = p value adjusted for multiple comparisons using the Benjamini-Hochberg False Discovery Rate method." 
  
```

```{r, results = "asis"}
res <-
  purrr::map2(list_titles, list_tables, function(x, y) {
  
  knitr::knit_child(text = c(
                    
                    "\n",
                    "# `r x`",
                    "\n",
                    "## Shift function",
                    "\n",
                    "```{r, echo = FALSE}",
                    "y$sf |> dplyr::mutate(
                    dplyr::across(`12`:ci_upper, ~round(.x, digits = 2)),
                    p_value = format(round(p_value, 3), nsmall = 3),
                    adj_p_value_bh = format(round(adj_p_value_bh, 3), nsmall = 3)
                    )",
                    "```",
                    "```{r, results='asis'}",
                    "cat(legend_sf)",
                    "```",
                    "\n",
                    "## Difference asymmetry function",
                    "\n",
                    "```{r, echo = FALSE}",
                    "y$daf |> dplyr::mutate(
                    dplyr::across(Est_q:ci.up, ~round(.x, digits = 2)),
                    p.value = format(round(p.value, 3), nsmall = 3),
                    adj_p_value_bh = format(round(adj_p_value_bh, 3), nsmall = 3)
                    )",
                    "```",
                    "```{r, results='asis'}",
                    "cat(legend_asym)",
                    "```"
  ),
  envir = environment(),
  quiet  = TRUE
  )
})

cat(unlist(res), sep = "\n")

```


