---
title: 'APA&Co project | SM7. Characteristics of the participants with missing data at 12 months'
output: 
  html_document:
    theme: cosmo
    toc: yes
    toc_depth: 2
    toc_float: yes
    number_sections: yes
    df_print: paged
    code_folding: hide
toc-title: "Table of content"
---
```{css, echo=FALSE}
.title {
  font-weight: bold;
}


h1 {
  font-size: 25px;
  font-weight: bold;
}
h2 {
  font-size: 23px;
  font-weight: bold;
}
h3 {
  font-size: 21px;
}
p.caption {
  color: #777;
  margin-top: 10px;
}
p code {
  white-space: inherit;
}
pre {
  word-break: normal;
  word-wrap: normal;
}
pre code {
  white-space: inherit;
}
```

```{r setup, include=FALSE}
# Set general settings
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
ggplot2::theme_set(ggplot2::theme_bw())

# Define a function to extract the IDs of the participants with missing data at follow-up
extract_missing_ids <- function(data1, data2, MONTH = "0") {
  
 ids_init <- 
  (data1 |> 
     dplyr::filter(MONTH == MONTH) |>  
     dplyr::mutate(patient = as.character(patient)) |>  
     dplyr::select(patient)
   )[[1]]
ids_final <- 
  (data2 |> 
     dplyr::filter(MONTH == MONTH) |>  
     dplyr::mutate(patient = as.character(patient)) |>  
     dplyr::select(patient)
   )[[1]]
ids_missing <- setdiff(ids_init, ids_final)  

return(ids_missing)
}

# Get data of interest
INCLUSION_cleaned <- tar_read(INCLUSION_cleaned) |> dplyr::select(-DIST_6WT_M0)
db_6MWT_init <- tar_read(DB_6MWT)
db_6MWT_final <- tar_read(DB_6MWT_0_12)
db_IPAQ_init <- tar_read(DB_IPAQ)
db_IPAQ_final <- tar_read(DB_IPAQ_6_12)
db_EMAPS_init <- tar_read(DB_EMAPS)
db_EMAPS_final <- tar_read(DB_EMAPS_0_12)
```

# Six-min walking test distance
```{r phys_char_missing_6MWT}
# Get IDs with missing data
ids_6MWT_missing <- extract_missing_ids(data1 = db_6MWT_init, data2 = db_6MWT_final)
db_6MWT_init$na_status <- ifelse(db_6MWT_init$patient %in% ids_6MWT_missing, "Incomplete", "Complete")
db_6MWT_init$na_status <- factor(db_6MWT_init$na_status, levels = c("Incomplete", "Complete"))

# Show descriptive statistics
INCLUSION_cleaned[INCLUSION_cleaned$patient %in% ids_6MWT_missing, ] |> 
  skimr::skim() |> 
  as.data.frame()
```

```{r plot_6MWT, fig.align="center"}
ggplot(data = db_6MWT_init |>  dplyr::filter(MONTH == "0"), aes(x = "", y = DIST_M, color = na_status)) +
  geom_boxplot(position = position_dodge(width = 0.75), width = 0.25, outlier.size = 0) +
  geom_point(position = position_jitterdodge(jitter.width = 0.05, dodge.width = 0.75)) +
  coord_flip() +
  scale_color_manual(values = c("red", "blue"), guide = guide_legend(reverse = TRUE)) +
  labs(title = "6MWT", x = NULL, y = "6-min walking distance (m)", color = "Data completness status") +
  theme(axis.ticks.y = element_blank())
```

## IPAQ-SF MET-min/week
```{r phys_char_missing_IPAQ}
# Get IDs with missing data
ids_IPAQ_missing <- extract_missing_ids(data1 = db_IPAQ_init, data2 = db_IPAQ_final, MONTH = "6")
db_IPAQ_init$na_status <- ifelse(db_IPAQ_init$patient %in% ids_IPAQ_missing, "Incomplete", "Complete")
db_IPAQ_init$na_status <- factor(db_IPAQ_init$na_status, levels = c("Incomplete", "Complete"))

# Show descriptive statistics
INCLUSION_cleaned[INCLUSION_cleaned$patient %in% ids_IPAQ_missing,] |> 
  skimr::skim() |> 
  as.data.frame()
```

```{r plot_IPAQ, fig.align="center"}
ggplot(data = db_IPAQ_init |>  dplyr::filter(MONTH == "0"), aes(x = "", y = MET_MIN_WK, color = na_status)) +
  geom_boxplot(position = position_dodge(width = 0.75), width = 0.25, outlier.size = 0) +
  geom_point(position = position_jitterdodge(jitter.width = 0.05, dodge.width = 0.75)) +
  coord_flip() +
  scale_color_manual(values = c("red", "blue"), guide = guide_legend(reverse = TRUE)) +
  labs(title = "IPAQ-SF", x = NULL, y = "IPAQ-SF (MET-min/week)", color = "Data completness status") +
  theme(axis.ticks.y = element_blank())
```

## EMAPS
```{r phys_char_missing_EMAPS}
# Get IDs with missing data
ids_EMAPS_missing <- extract_missing_ids(data1 = db_EMAPS_init, data2 = db_EMAPS_final)
db_EMAPS_init$na_status <- ifelse(db_EMAPS_init$patient %in% ids_EMAPS_missing, "Incomplete", "Complete")
db_EMAPS_init$na_status <- factor(db_EMAPS_init$na_status, levels = c("Incomplete", "Complete"))

# Show descriptive statistics
INCLUSION_cleaned[INCLUSION_cleaned$patient %in% ids_EMAPS_missing,] |> 
  skimr::skim() |> 
  as.data.frame()
```

```{r plot_EMAPS, fig.align="center"}
ggplot(data = db_EMAPS_init |>  
         dplyr::filter(MONTH == "0") |> 
         tidyr::pivot_longer(
           cols = c(INTRINSIC:AMOTIVATION), 
           names_to = "type_motivation", 
           values_to = "Score"
           ) |> 
         dplyr::mutate(type_motivation = factor(type_motivation, levels = c("INTRINSIC", "INTEGRATED", "IDENTIFIED", "INTROJECTED", "EXTERNAL", "AMOTIVATION"))), 
       
       aes(x = "", y = Score, color = na_status)) +
  geom_boxplot(position = position_dodge(width = 0.75), width = 0.25, outlier.size = 0) +
  geom_point(position = position_jitterdodge(jitter.width = 0.05, dodge.width = 0.75)) +
  coord_flip() +
  scale_color_manual(values = c("red", "blue"), guide = guide_legend(reverse = TRUE)) +
  labs(title = "EMAPS", x = NULL, color = "Data completness status") +
  theme(axis.ticks.y = element_blank()) +
  facet_wrap(~ type_motivation)
```

