name: build_docker

on:
  push:
    branches:
      - master
      - pipeline

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: apaco_project
    steps:
      - name: Setup
        uses: docker/setup-buildx-action@v2

      - name: Docker Run Action
        run: >
          docker run --rm --name apaco_container -v
          github/workspace/shared_folder:/project/shared_folder:rw
          apaco_image

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}
          push: true

      - uses: actions/uplolad-artifact@v3
        with:
          name: apaco_output_${{ github.sha }}
          path: /github/workspace/shared_folder

